# Generated by Django 5.2.7 on 2025-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFComoarision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file_1', models.FileField(upload_to='pdfs/')),
                ('pdf_file_2', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_identical', models.DateTimeField(null=True)),
                ('comparison_result', models.TextField(blank=True)),
                ('comparision_type', models.CharField(choices=[('byte', 'Byte'), ('text', 'Text'), ('visual', 'visual')], default='byte', max_length=10)),
            ],
        ),
    ]
