# Generated by Django 5.2.7 on 2025-10-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFComoarision',
            new_name='PDFComparision',
        ),
    ]
