# Generated by Django 5.2.7 on 2025-10-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0002_rename_pdfcomoarision_pdfcomparision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcomparision',
            name='comparision_type',
            field=models.CharField(choices=[('byte', 'Byte'), ('text', 'Text'), ('visual', 'Visual')], default='byte', max_length=10),
        ),
    ]
